#!/bin/sh

# load $WALLPAPER_IMAGE environment variable
source $HOME/.config/hypr/scripts/variables/load_envs

function load_wp(){
    swww img -t simple --transition-speed 100 --transition-step 255 --transition-fps 30 $BACKGROUND_IMAGE
}

#perform cleanup and exit
if ! swww query; then
    swww init
fi

load_wp
